name: Build

on:
  push:
    branches: [ release ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  MODULE_NAME: auto-reboot-if-overload

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
        #   node-version: [18.x, 20.x, 22.x]
          node-version: [22.x]

    steps:
      - name: Pull source
        uses: actions/checkout@v4

      - name: Go to /src/webroot-vue
        run: cd ./src/webroot-vue

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install
        
      - name: Build WebUI
        run: npm vite build
        
      - name: Create Module Package
        run: |
          cd ../../
          cp -r ./src/webroot/ ./build/webroot/
          cp ./src/config.conf ./build/
          cp ./src/module.prop ./build/
          cp ./src/service.sh ./build/
          cd build
          zip -r ../$MODULE_NAME.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: $MODULE_NAME
          path: $MODULE_NAME.zip
